/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fincker.app;

/**
 *
 * @author USER
 */
public class laporanView extends javax.swing.JFrame {

    /**
     * Creates new form laporanView
     */
    public laporanView() {
        initComponents();
        
        this.setSize(1280, 720);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bg = new javax.swing.JPanel() {
            // 1. Muat Gambar (Ganti nama file sesuai punyamu)
            java.awt.Image backgroundImage = new javax.swing.ImageIcon(getClass().getResource("/fincker/app/gambar/bg-laporan.gif")).getImage();

            // 2. Timpa cara menggambar Panel
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g); // Gambar panel dasar dulu

                // Gambar background melar memenuhi panel
                g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
            }
        };
        pnlNavbar = new javax.swing.JPanel();
        btnBeranda = new javax.swing.JButton();
        btnTentang = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnTabungan = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        pnlLaporan = new javax.swing.JPanel();
        pnlStatistik = new javax.swing.JPanel();
        pnlMasuk = new javax.swing.JPanel();
        lblTotalMasuk = new javax.swing.JLabel();
        pnlKeluar = new javax.swing.JPanel();
        lblTotalKeluar = new javax.swing.JLabel();
        pnlSaldo = new javax.swing.JPanel();
        lblSisaSaldo = new javax.swing.JLabel();
        pnlGrafik = new javax.swing.JPanel();
        scpTabel = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        bg.setBackground(new java.awt.Color(0, 102, 102));
        bg.setPreferredSize(new java.awt.Dimension(1280, 720));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNavbar.setBackground(new java.awt.Color(153, 255, 255));
        pnlNavbar.setOpaque(false);
        pnlNavbar.setPreferredSize(new java.awt.Dimension(1200, 70));

        btnBeranda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBeranda.setText("Beranda");
        btnBeranda.setBorderPainted(false);
        btnBeranda.setContentAreaFilled(false);
        btnBeranda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBeranda.setFocusPainted(false);
        btnBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerandaActionPerformed(evt);
            }
        });

        btnTentang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTentang.setText("Tentang");
        btnTentang.setBorderPainted(false);
        btnTentang.setContentAreaFilled(false);
        btnTentang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTentang.setFocusPainted(false);
        btnTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTentangActionPerformed(evt);
            }
        });

        btnLaporan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLaporan.setText("Laporan");
        btnLaporan.setBorderPainted(false);
        btnLaporan.setContentAreaFilled(false);
        btnLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporan.setFocusPainted(false);
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        btnTabungan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTabungan.setText("Tabungan");
        btnTabungan.setBorderPainted(false);
        btnTabungan.setContentAreaFilled(false);
        btnTabungan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTabungan.setFocusPainted(false);
        btnTabungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabunganActionPerformed(evt);
            }
        });

        btnProfile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnProfile.setText("Profile");
        btnProfile.setBorderPainted(false);
        btnProfile.setContentAreaFilled(false);
        btnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfile.setFocusPainted(false);
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNavbarLayout = new javax.swing.GroupLayout(pnlNavbar);
        pnlNavbar.setLayout(pnlNavbarLayout);
        pnlNavbarLayout.setHorizontalGroup(
            pnlNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavbarLayout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addComponent(btnBeranda)
                .addGap(97, 97, 97)
                .addComponent(btnTentang, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(btnLaporan)
                .addGap(110, 110, 110)
                .addComponent(btnTabungan)
                .addGap(91, 91, 91)
                .addComponent(btnProfile)
                .addGap(81, 81, 81))
        );
        pnlNavbarLayout.setVerticalGroup(
            pnlNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavbarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBeranda, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTentang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLaporan)
                    .addComponent(btnTabungan)
                    .addComponent(btnProfile))
                .addGap(32, 32, 32))
        );

        bg.add(pnlNavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 80));

        pnlLaporan.setOpaque(false);
        pnlLaporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlStatistik.setLayout(new java.awt.GridBagLayout());

        pnlMasuk.setBackground(new java.awt.Color(255, 51, 51));

        lblTotalMasuk.setText("Pemasukan");
        pnlMasuk.add(lblTotalMasuk);

        pnlStatistik.add(pnlMasuk, new java.awt.GridBagConstraints());

        pnlKeluar.setBackground(new java.awt.Color(51, 51, 255));

        lblTotalKeluar.setText("Pengeluaran");
        pnlKeluar.add(lblTotalKeluar);

        pnlStatistik.add(pnlKeluar, new java.awt.GridBagConstraints());

        pnlSaldo.setBackground(new java.awt.Color(51, 255, 102));

        lblSisaSaldo.setText("Saldo Akhir");
        pnlSaldo.add(lblSisaSaldo);

        pnlStatistik.add(pnlSaldo, new java.awt.GridBagConstraints());

        pnlLaporan.add(pnlStatistik, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 590, 270));

        javax.swing.GroupLayout pnlGrafikLayout = new javax.swing.GroupLayout(pnlGrafik);
        pnlGrafik.setLayout(pnlGrafikLayout);
        pnlGrafikLayout.setHorizontalGroup(
            pnlGrafikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlGrafikLayout.setVerticalGroup(
            pnlGrafikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlLaporan.add(pnlGrafik, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 590, 270));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scpTabel.setViewportView(jTable1);

        pnlLaporan.add(scpTabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 1180, 190));

        bg.add(pnlLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 80, 1280, 640));

        getContentPane().add(bg, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerandaActionPerformed
        // TODO add your handling code here:
        // 1. Panggil method loadData() yang sudah kita buat sebelumnya
        // Karena kita sudah ada di Beranda, cukup refresh data saja
        new dashboardView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBerandaActionPerformed

    private void btnTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentangActionPerformed
        // TODO add your handling code here:
        // 1. Buka View Tujuan
        new tentangView().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnTentangActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
        updateTampilan();
        initTanggal();
        javax.swing.JOptionPane.showMessageDialog(this, "Tampilan berhasil diperbarui!");
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnTabunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabunganActionPerformed
        // TODO add your handling code here:
        new wishlistView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTabunganActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        new profileView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporanView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnBeranda;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnTabungan;
    private javax.swing.JButton btnTentang;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSisaSaldo;
    private javax.swing.JLabel lblTotalKeluar;
    private javax.swing.JLabel lblTotalMasuk;
    private javax.swing.JPanel pnlGrafik;
    private javax.swing.JPanel pnlKeluar;
    private javax.swing.JPanel pnlLaporan;
    private javax.swing.JPanel pnlMasuk;
    private javax.swing.JPanel pnlNavbar;
    private javax.swing.JPanel pnlSaldo;
    private javax.swing.JPanel pnlStatistik;
    private javax.swing.JScrollPane scpTabel;
    // End of variables declaration//GEN-END:variables

    private void updateTampilan() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void initTanggal() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
