/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fincker.app;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Aziz
 */
public class registerView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(registerView.class.getName());
    public static ArrayList<User> listUser = new ArrayList<>();

    /**
     * Creates new form registerView
     */
    public registerView() {
        initComponents();
        this.setSize(1280, 720);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            // 1. Muat Gambar (Ganti nama file sesuai punyamu)
            java.awt.Image backgroundImage = new javax.swing.ImageIcon(getClass().getResource("/fincker/app/gambar/bg-logreg.gif")).getImage();

            // 2. Timpa cara menggambar Panel
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g); // Gambar panel dasar dulu

                // Gambar background melar memenuhi panel
                g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
            }
        };
        pnlRegister = new javax.swing.JPanel();
        txtNama = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtKonfirmasi = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtTelp = new javax.swing.JTextField();
        txtPekerjaan = new javax.swing.JTextField();
        lblTelpon = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblPekerjaan = new javax.swing.JLabel();
        lblLahir = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblKonfirmasi = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        dcLahir = new com.toedter.calendar.JDateChooser();
        lblRegister = new javax.swing.JLabel();
        cbShowPass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRegister.setBackground(new java.awt.Color(153, 204, 255));

        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtKonfirmasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtKonfirmasi.addActionListener(this::txtKonfirmasiActionPerformed);

        btnRegister.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegister.setText("DAFTAR");
        btnRegister.addActionListener(this::btnRegisterActionPerformed);

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancel.setText("KEMBALI");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        txtTelp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtPekerjaan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTelpon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelpon.setText("No. Telpon");

        lblNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNama.setText("Nama Lengkap");

        lblPekerjaan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPekerjaan.setText("Pekerjaan");

        lblLahir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLahir.setText("Tanggal Lahir");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setText("Email");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblKonfirmasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKonfirmasi.setText("Konfirmasi Password");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPassword.setText("Password");

        lblRegister.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRegister.setText("REGISTRASI");

        cbShowPass.setText("Lihat");
        cbShowPass.addActionListener(this::cbShowPassActionPerformed);

        javax.swing.GroupLayout pnlRegisterLayout = new javax.swing.GroupLayout(pnlRegister);
        pnlRegister.setLayout(pnlRegisterLayout);
        pnlRegisterLayout.setHorizontalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                        .addComponent(lblRegister)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                                .addComponent(lblNama)
                                .addGap(69, 69, 69))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createSequentialGroup()
                                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPassword)
                                    .addComponent(lblKonfirmasi))
                                .addGap(35, 35, 35))
                            .addGroup(pnlRegisterLayout.createSequentialGroup()
                                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPekerjaan)
                                    .addComponent(lblLahir)
                                    .addComponent(lblTelpon)
                                    .addComponent(lblEmail))
                                .addGap(79, 79, 79)))
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPekerjaan)
                                .addComponent(txtEmail)
                                .addComponent(txtPassword)
                                .addComponent(txtKonfirmasi)
                                .addComponent(dcLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbShowPass, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(40, 40, 40))))
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btnCancel)
                .addGap(60, 60, 60)
                .addComponent(btnRegister)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlRegisterLayout.setVerticalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblRegister)
                .addGap(55, 55, 55)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(dcLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addComponent(lblNama)
                        .addGap(28, 28, 28)
                        .addComponent(lblTelpon)
                        .addGap(33, 33, 33)
                        .addComponent(lblLahir)))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPekerjaan))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addGap(21, 21, 21)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(30, 30, 30)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKonfirmasi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbShowPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnCancel))
                .addGap(49, 49, 49))
        );

        jPanel1.add(pnlRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 490, 570));

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKonfirmasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKonfirmasiActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    // 1. AMBIL DATA
        String nama = txtNama.getText();
        String telp = txtTelp.getText();
        String pekerjaan = txtPekerjaan.getText();
        String email = txtEmail.getText();
        String pass = new String(txtPassword.getPassword());
        String konfirmasi = new String(txtKonfirmasi.getPassword());

        // Ambil Tanggal
        String tglLahir = "";
        if (dcLahir.getDate() != null) {
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MM-yyyy");
            tglLahir = sdf.format(dcLahir.getDate());
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Tanggal Lahir belum dipilih!");
            return;
        }

        // 2. VALIDASI KOSONG
        if (nama.isEmpty() || telp.isEmpty() || pekerjaan.isEmpty() || email.isEmpty() || pass.isEmpty() || konfirmasi.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Harap isi semua data!");
            return;
        }
        
        // Validasi Email Sederhana
if (!email.contains("@") || !email.contains(".")) {
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Format Email salah! Haruss mengandung '@' dan domain (contoh: .com)", 
        "Validasi Gagal", javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}

        // 3. VALIDASI PASSWORD
        if (!pass.equals(konfirmasi)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Password tidak cocok!");
            txtPassword.setText("");
            txtKonfirmasi.setText("");
            return;
        }

        // 4. SIMPAN DATA (Tanpa Username)
        User newUser = new User(nama, email, telp, pekerjaan, tglLahir, pass);
        listUser.add(newUser);

        javax.swing.JOptionPane.showMessageDialog(this, "Registrasi Berhasil! Silakan Login dengan Email.");

        // 5. PINDAH KE LOGIN
        new loginView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void cbShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPassActionPerformed
        // TODO add your handling code here:
        // Cek: Apakah kotak dicentang?
        if (cbShowPass.isSelected()) {
            // Jika dicentang, BUKA dua-duanya
            txtPassword.setEchoChar((char) 0); 
            txtKonfirmasi.setEchoChar((char) 0); // Pastikan nama variabelnya benar (txtKonfirmasi atau txtRetype)
        } else {
            // Jika tidak dicentang, TUTUP dua-duanya
            txtPassword.setEchoChar('*'); 
            txtKonfirmasi.setEchoChar('*'); 
        }
    }//GEN-LAST:event_cbShowPassActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        loginView lv = new loginView();
        lv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new registerView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JCheckBox cbShowPass;
    private com.toedter.calendar.JDateChooser dcLahir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblKonfirmasi;
    private javax.swing.JLabel lblLahir;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPekerjaan;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblTelpon;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtKonfirmasi;
    private javax.swing.JTextField txtNama;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPekerjaan;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables
}
