/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fincker.app;

/**
 *
 * @author Muham
 */
public class tentangView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tentangView.class.getName());

    /**
     * Creates new form tentangView
     */
    public tentangView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel() {
            // 1. Muat Gambar (Ganti nama file sesuai punyamu)
            java.awt.Image backgroundImage = new javax.swing.ImageIcon(getClass().getResource("/fincker/app/gambar/bg-tentang-profile.gif")).getImage();

            // 2. Timpa cara menggambar Panel
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g); // Gambar panel dasar dulu

                // Gambar background melar memenuhi panel
                g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jPanel2 = new javax.swing.JPanel();
        lblFoto1 = new javax.swing.JLabel();
        lblFoto2 = new javax.swing.JLabel();
        lblFoto3 = new javax.swing.JLabel();
        lblNama1 = new javax.swing.JLabel();
        lblNama2 = new javax.swing.JLabel();
        lblNama3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fincker/app/gambar/1.jpg"))); // NOI18N
        lblFoto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblFoto1.setPreferredSize(new java.awt.Dimension(650, 650));
        jPanel2.add(lblFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 140, 140));

        lblFoto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fincker/app/gambar/3.jpg"))); // NOI18N
        lblFoto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblFoto2.setPreferredSize(new java.awt.Dimension(650, 650));
        jPanel2.add(lblFoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 140, 140));

        lblFoto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fincker/app/gambar/2.jpg"))); // NOI18N
        lblFoto3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblFoto3.setPreferredSize(new java.awt.Dimension(650, 650));
        jPanel2.add(lblFoto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 140, 140));

        lblNama1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNama1.setText("Rizky");
        jPanel2.add(lblNama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        lblNama2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNama2.setText("Rahma");
        jPanel2.add(lblNama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        lblNama3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNama3.setText("Aziz");
        jPanel2.add(lblNama3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 830, 280));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("FinCker (Financial Tracker) adalah aplikasi manajemen keuangan cerdas yang dirancang untuk membantu pengguna umum dalam mencatat arus kas harian. Dilengkapi dengan fitur pencatatan Pemasukan, Pengeluaran, serta Tabungan Impian (Wishlist), FinCker hadir sebagai solusi praktis untuk menciptakan kebiasaan finansial yang lebih sehat, transparan, dan terencana.");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 830, 60));

        getContentPane().add(jPanel1, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new tentangView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblFoto1;
    private javax.swing.JLabel lblFoto2;
    private javax.swing.JLabel lblFoto3;
    private javax.swing.JLabel lblNama1;
    private javax.swing.JLabel lblNama2;
    private javax.swing.JLabel lblNama3;
    // End of variables declaration//GEN-END:variables
}
