/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fincker.app;

/**
 *
 * @author Muham
 */
public class welcomeView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(welcomeView.class.getName());

    /**
     * Creates new form welcomeView
     */
    public welcomeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblTagline = new javax.swing.JLabel();
        btnMulai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("FINCKER");
        jPanel1.add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        lblTagline.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTagline.setForeground(new java.awt.Color(255, 255, 255));
        lblTagline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTagline.setText("Solusi Cerdas Keuangan Anda.");
        jPanel1.add(lblTagline, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        btnMulai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMulai.setText("MULAI SEKARANG");
        btnMulai.addActionListener(this::btnMulaiActionPerformed);
        jPanel1.add(btnMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 210, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulaiActionPerformed
    // TODO add your handling code here:
    // 1. Siapkan halaman Login
    loginView loginPage = new loginView();
    
    // 2. Trik agar Login muncul pas di tengah layar (biar transisinya mulus)
    loginPage.setLocationRelativeTo(null);
    
    // 3. Tampilkan halaman Login
    loginPage.setVisible(true);
    
    // 4. Tutup halaman Welcome (agar tidak menumpuk di memori)
    this.dispose();
    }//GEN-LAST:event_btnMulaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new welcomeView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMulai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblTagline;
    // End of variables declaration//GEN-END:variables
}
